/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.civfanatics.civ3.xplatformeditor.tabs.map;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JFrame;

/**
 *
 * @author Andrew
 */
public class ColourChooser extends javax.swing.JDialog {

    boolean okToClose = false;
    /**
     * Creates new form ColourChooser
     */
    public ColourChooser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Color Chooser");
        this.addWindowListener(new WindowListener() {

            public void windowOpened(WindowEvent e)
            {
                ;
            }

            public void windowClosing(WindowEvent e)
            {
                if (!okToClose)
                    setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                else
                    setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            }

            public void windowClosed(WindowEvent e)
            {
                ;
            }

            public void windowIconified(WindowEvent e)
            {
                ;
            }

            public void windowDeiconified(WindowEvent e)
            {
                ;
            }

            public void windowActivated(WindowEvent e)
            {
                ;
            }

            public void windowDeactivated(WindowEvent e)
            {
                ;
            }
        });
        
        cmdOK.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e)
            {
                okToClose = true;
                setVisible(false);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jccChooser = new javax.swing.JColorChooser();
        cmdOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        getContentPane().add(jccChooser, gridBagConstraints);

        cmdOK.setText("OK");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        getContentPane().add(cmdOK, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdOK;
    private javax.swing.JColorChooser jccChooser;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void setVisible(boolean visible)
    {
        super.setVisible(visible);
        //do extra stuff
        okToClose = false;
    }
    
    public Color getColor()
    {
        return jccChooser.getColor();
    }
    
    public void setColor(Color c)
    {
        jccChooser.setColor(c);
    }
}
