/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.civfanatics.civ3.xplatformeditor.tabs.map;

import com.civfanatics.civ3.biqFile.IO;
import com.civfanatics.civ3.xplatformeditor.Main;

/**
 *
 * @author Andrew
 */
public class PolarBearForm extends javax.swing.JFrame {

    IO biq = null;
    
    /**
     * Creates new form PolarBearForm
     */
    public PolarBearForm() {
        initComponents();
        cmbMapSize.removeAllItems();
        biq = Main.biqFile.get(Main.biqIndex);
        for (int i =  0; i < biq.worldSize.size(); i++)
        {
            cmbMapSize.addItem(biq.worldSize.get(i).getName());
        }
        cmbMapSize.setSelectedIndex(biq.worldCharacteristic.get(0).getWorldSize());
        chkPolarIce.setSelected(biq.worldMap.get(0).polarIceCaps);
        chkXWrap.setSelected(biq.worldMap.get(0).xWrapping);
        chkYWrap.setSelected(biq.worldMap.get(0).yWrapping);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        chkYWrap = new javax.swing.JCheckBox();
        chkPolarIce = new javax.swing.JCheckBox();
        chkXWrap = new javax.swing.JCheckBox();
        lblMapSize = new javax.swing.JLabel();
        cmbMapSize = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Map Properties");
        setMinimumSize(new java.awt.Dimension(200, 200));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        chkYWrap.setText("Y-Wrapping");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(chkYWrap, gridBagConstraints);

        chkPolarIce.setText("Polar Ice");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(chkPolarIce, gridBagConstraints);

        chkXWrap.setText("X-Wrapping");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(chkXWrap, gridBagConstraints);

        lblMapSize.setText("Map Size:");
        lblMapSize.setToolTipText("This corresponds with WSIZ settings, and affects optimal city number, etc.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(lblMapSize, gridBagConstraints);

        cmbMapSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(cmbMapSize, gridBagConstraints);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(jButton1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        biq.worldMap.get(0).polarIceCaps = chkPolarIce.isSelected();
        biq.worldMap.get(0).xWrapping = chkXWrap.isSelected();
        biq.worldMap.get(0).yWrapping = chkYWrap.isSelected();
        biq.worldMap.get(0).calculateFlags();
        biq.worldCharacteristic.get(0).setWorldSize(cmbMapSize.getSelectedIndex());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolarBearForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolarBearForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolarBearForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolarBearForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PolarBearForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkPolarIce;
    private javax.swing.JCheckBox chkXWrap;
    private javax.swing.JCheckBox chkYWrap;
    private javax.swing.JComboBox cmbMapSize;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblMapSize;
    // End of variables declaration//GEN-END:variables
}
